SELECT COUNT( DISTINCT _case_concept_name_) AS CLUSTER_01_01_01_compliant_INV_after_GR_with_SRM_Service FROM
PROM.CLUSTER_01_01_01_compliant_INV_after_GR_with_SRM_Service

SELECT COUNT( DISTINCT _case_concept_name_) AS CLUSTER_01_01_01_compliant_INV_after_GR_with_SRM_Service FROM
PROM.CLUSTER_01_01_01_compliant_INV_after_GR_with_SRM_Service

SELECT COUNT( DISTINCT _case_concept_name_) AS CLUSTER_01_03_01_compliant_INV_after_GR_Framework_order_Service FROM
PROM.CLUSTER_01_03_01_compliant_INV_after_GR_Framework_order_Service


SELECT COUNT( DISTINCT _case_concept_name_) AS CLUSTER_01_02_01_compliant_INV_after_GR_Standard_PO_Service FROM
PROM.CLUSTER_01_02_01_compliant_INV_after_GR_Standard_PO_Service

SELECT COUNT( DISTINCT _case_concept_name_) AS CLUSTER_01_02_01_compliant_INV_after_GR_Standard_PO_Service FROM
PROM.CLUSTER_01_02_02_compliant_INV_after_GR_without_SRM_Standard

SELECT COUNT( DISTINCT _case_concept_name_) AS CLUSTER_02_02_02_compliant_INV_before_GR_without_SRM_Subcontracting FROM
PROM.CLUSTER_02_02_02_compliant_INV_before_GR_without_SRM_Subcontracting


SELECT COUNT( DISTINCT _case_concept_name_) AS CLUSTER_02_02_01_compliant_INV_before_GR_without_SRM_Standard FROM
PROM.CLUSTER_02_02_01_compliant_INV_before_GR_without_SRM_Standard

SELECT COUNT( DISTINCT _case_concept_name_) AS CLUSTER_02_02_01_compliant_INV_before_GR_without_SRM_Standard_Filtered FROM
PROM.CLUSTER_02_02_01_compliant_INV_before_GR_without_SRM_Standard_Filtered